Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "pages#home", as: "root"
  # get "/milkshakes", to: "milkshakes#index", as: "milkshakes"
  # get "/milkshakes/new", to: "milkshakes#new", as: "new_milkshake"
  # get "/milkshakes/:id", to: "milkshakes#show", as: "milkshake"
  # post "/milkshakes", to: "milkshakes#create"
  # patch "/milkshakes/:id", to: "milkshakes#update"
  # get "/milkshakes/:id/edit", to: "milkshakes#edit", as: "edit_milkshakes"

  get "/museums", to: "museums#index", as: "museums"
  post "/museums", to: "museums#create"
  get "/museum/new", to: "museums#new", as: "new_museums"
  get "/museums/:id/edit", to: "museums#edit", as: "edit_museum"
  get "/museums/:id", to: "museums#show", as: "museum"
  patch "/museums/:id", to: "museums#update"
  put "/museums/:id", to: "museums#update"
  delete "/museums/:id", to: "museums#destroy"
  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#creat"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  patch "/listings/:id", to: "listings#update"
  put "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"
  get "/styles", to: "styles#index", as: "styles"
  get "/styles/:id", to: "styles#show", as: "style"
  get "/payments/:id", to: "payments#show", as: "payment"
  get "payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"
end
